
drop table comment if exists;
drop table thread if exists;
drop table user if exists;

-- 用户
create table user(
    username varchar(100), -- 帐号
    password varchar(100), -- 密码
    reg_time datetime, -- 注册时间
    last_login datetime, -- 上次登录时间
	state integer, -- 账户状态
	level integer, -- 账户级别
	hit integer, -- 登陆次数
	realname varchar(100) -- 真实姓名
);
alter table user
    add constraint pk_user primary key (id);
alter table user
    alter column id bigint generated by default as identity (start with 1, increment by 1);
	
insert into user (
    username,password,reg_time,last_login,state,level,hit
) values (
    'admin','fenghuo110','2008-04-06 21:15:00','2008-04-06 21:15:00',0,1,0
);


-- 登陆日志
create table thread(
    login_reason varchar(2000), -- 登陆理由
    login_time datetime, -- 登陆时间
    username varchar(100), --用户名
    login_mac varchar(30) -- 登陆MAC
);
alter table thread
    add constraint pk_thread primary key (id);
alter table thread
    alter column id bigint generated by default as identity (start with 1, increment by 1);
alter table thread
    add constraint fk_thread_user
    foreign key (user) references user (id);


commit;

shutdown;
